
a=int(input("Введите значение a:"))
b=int(input("Введите значение b:"))
print("Сумма a+b")
print(a+b)
print("Вычитание a-b")
print(a-b)
print("Умножение a*b")
print(a*b)
print("Деление a/b")
print(a/b)
